### ISSUE TITLE
Inconsistencies between naming in mongoose-ds and Bb

### ISSUE THREAD

**Issue by EugeneButusov** [vedi/restifizer-mongoose-ds#4]
Please have a look at this: https://github.com/vedi/restifizer-mongoose-ds/blob/master/lib/mongoose-data-source.js#L53

As I understand, by convention given from Bluebird, promisified methods has `Async` postfix. Here is example of async method but named like sync. It brings troubles in code after `Bb.PromisifyAll(mongooseDS)` and calling `findOneAsync` then.

Maybe it should be noticed in docs or fixed in code.

**Comment by vedi** [comment]
@EugeneButusov, it's not relevant I guess?

**Comment by EugeneButusov** [comment]
yes sorry, forgot to close it.
